# Description:
#   To wow the laydeez
#
# Author:
#   akshay

module.exports = (robot) ->

  PICKUPLINES = [
    "Your legs must be tired because you\'ve been running through my mind all night.",
    "Was your father a thief? \'Cause someone stole the stars from the sky and put them in your eyes.",
    "Do you have a pencil? Cause I want to erase your past and write our future.",
    "I love you like a pig loves not being bacon.",
    "Are your parents bakers? Cause they sure made you a cutie pie!",
    "Did you go to bed early last night? From the looks of it, you got your beauty sleep.",
    "What\'s on the menu? Me-n-U",
    "You\'re like pizza. Even when you are bad, you\'re good",
    "I\'d say God Bless you, but it looks like he already did.",
    "I must be in a museum, because you truly are a work of art.",
    "My friend thinks you\'re kinda cute, but I don\'t... I think you\'re absolutely gorgeous!",
    "Let\'s commit the perfect crime: I\'ll steal your heart, and you\'ll steal mine.",
    "You spend so much time in my mind, I should charge you rent.",
    "If kisses were snowflakes, I\'d send you a blizzard",
    "Are you my phone charger? Because without you, I\'d die.",
    "How come you\'re not on top of a Christmas tree? I thought that\'s where angels belonged.",
    "Are you a hipster, because you make my hips stir.",
    "Are you a cat? Cause you are purrrfect",
    "Does your father sell diamonds? Because you are FLAWLESS!",
    "If you were a tropical fruit, you\'d be a Fine-apple!",
    "I wish I was cross eyed, so I could see you twice.",
    "Are you on Nickelodeon? Cause you\'re a-Dora-ble!",
    "I don\'t know if you\'re beautiful, I haven\'t gotten past your eyes yet.",
    "You don\'t need keys to drive me crazy.",
    "My name isn\'t Elmo, but you can tickle me any time you want to.",
    "Can you take me to the doctor? Because I just broke my leg falling for you.",
    "People call me John, but you can call me tonight.",
    "You must be a ninja, because you snuck into my heart",
    "I need a dollar, but I only have 90 cents... do you want to be my dime?",
    "Are you a magician??? Because Abraca-DAYUM!",
    "You\'re so hot, that if you ate a piece of bread, you\'d poop out toast!",
    "Be unique and different, say yes.",
    "Your eyes are blue, like the ocean. And baby, I\'m lost at sea.",
    "You know how they say skin is the largest organ on the human body? Not in my case.",
    "My lips are like skittles. Wanna taste the rainbow?",
    "They say dating is a numbers game... so can I get your number?",
    "My name isn\'t Elmo, but you can tickle me any time you want to.",
    "You be the Dairy Queen and I\'ll be your Burger King: You treat me right, and I\'ll do it your way.",
    "if I had to choose between breathing or loving you, I would say \"I love you\" with my last breath!",
    "You must be from Pearl Harbor, because baby, you\'re the bomb.",
    "You must be Jamaican, because Jamaican me crazy.",
    "Do you know karate? Because your body is really kickin\'.",
    "When God made you, he was showing off.",
    "Are you a Snickers bar? Cause you satisfy me.",
    "Is your dad a terrorist? Because you are the bomb.",
    "Is your last name Campbell? Cause you\'re \"mmmm... good!\"",
    "You\'re like a dictionary, you add meaning to my life!",
    "Baby, you are so fine I could put you on a plate and sop you up with a biscuit.",
    "Is there a rainbow today? I just found the treasure I\'ve been searching for!",
    "You remind me of a magnet, because you sure are attracting me over here!",
    "Hey, is it just me, or are we destined to be married?",
    "Hello. Are you taking any applications for a boy/girlfriend?",
    "I have an \"owie\" on my lip. Will you kiss it and make it better?",
    "Let\'s make like a fabric softener and \'Snuggle",
    "I didn\'t see any stars in the sky tonight, the most heavenly body was standing right next to me.",
    "Hi, my name is Doug. That\'s \"god\" spelled backwards with a little bit of you wrapped up in it.",
    "If I could reach out and hold a star for everytime you\'ve made me smile, I\'d hold the sky in the palm of my hand.",
    "Well, here I am. What were your other two wishes?",
    "Should I smile because we are friends, or cry because I know that is what we will ever be?",
    "When I look into your eyes, it is like a gateway into the world of which I want to be a part.",
    "Hello, I\'m doing a survey of what people think are the cheesiest pickup lines. So, do you pick \'Do you come here often?\', \'What\'s your sign?\', or \'Hello, I\'m doing a survey of what people think are the cheesiest pickup lines.\'?",
    "This time next year let’s be laughing together.",
    "Let me tie your shoes, cause I dont want you falling for anyone else.",
    "On a scale of 1 to 10, you\'re a 9. I\'m the 1 you need.",
    "Most guys need 3 meals a day to keep going... I just need eye contact from you.",
    "Hey baby, I must be a light switch, cuz every time I see you, you turn me on!",
    "Are you a beaver? Cause daaaaam!",
    "I hope your day has been as beautiful as you are.",
    "Do I know you? Cause you look just like my next girlfriend.",
    "Is your father Little Caesar? Cause you look Hot \'n Ready.",
    "I could use some spare change and you\'re a dime.",
    "I\'m no mathematician, but I\'m pretty good with numbers. Tell you what, Give me yours and watch what I can do with it.",
    "Didn\'t I see you on the cover of Vogue?",
    "Excuse me, I don\'t want you to think I\'m ridiculous or anything, but you are the most beautiful woman I have ever seen. I just felt like I had to tell you.",
    "Have you always been this cute, or did you have to work at it?",
    "Hey, don\'t I know you? Yeah, you\'re the girl with the beautiful smile.",
    "Was your father a mechanic? Then how did you get such a finely tuned body?",
    "I have had a really bad day and it always makes me feel better to see a pretty girl smile. So, would you smile for me?",
    "I hope you know CPR, cuz you take my breath away!",
    "I just had to come talk with you. Sweetness is my weakness.",
    "I think I can die happy now, cause I\'ve just seen a piece of heaven.",
    "Apart from being sexy, what do you do for a living?",
    "If I told you that you had a great body, would you hold it against me?",
    "I sneezed because God blessed me with you.",
    "Is it hot in here or is it just you?",
    "So, what do you do for a living besides always making all the men excited and warm all over?",
    "I may not be a genie, but I can make all your wishes come true!",
    "Was your dad king for a day? He must have been to make a princess like you.",
    "Were you arrested earlier? It\'s gotta be illegal to look that good.",
    "Were your parents Greek Gods, \'cause it takes two gods to make a goddess.",
    "What does it feel like to be the most beautiful girl in this room?",
    "What\'s that on your face? Oh, must just be beauty. Here, let me get it off. Hey, it\'s not coming off!",
     "I blame you for global warming... your hotness is too much for the planet to handle!",
    "You are the reason men fall in love.",
    "Are you Australian? Because you meet all of my koala-fications.",
    "You know the more I drink, the prettier you get!",
    "If you were ground coffee, you\'d be Espresso cause you\'re so fine.",
    "You better call Life Alert, \'cause I\'ve fallen for you and I can\'t get up.",
    "You\'re single. I\'m single. Coincidence? I think not.",
    "You know, you might be asked to leave soon. You\'re making the other women look really bad.",
    "You make me melt like hot fudge on a sundae.",
    "You should be someone\'s wife.",
    "Were you in Boy Scouts? Because you sure have tied my heart in a knot.",
    "Are you as beautiful on the inside as you are on the outside?",
    "I want to be your tear drop, so I could be born in your eyes, live on your cheeks, and die on your lips.",
    "Babe! you look so fine I could drink your bath water!",
    "You\'re so hot you would make the devil sweat.",
    "If I had a rose for every time I thought of you, I would be walking through my garden forever.",
    "Hi, I\'m writing a term paper on the finer things in life, and I was wondering if I could interview you?",
    "Girl, if I were a fly, I\'d be all over you, because you\'re the shit!",
    "There must be a lightswitch on my forehead because everytime I see you, you turn me on!",
     "Damn girl, you have more curves than a race track.",
    "If you stood in front of a mirror and help up 11 roses, you would see 12 of the most beautiful things in the world.",
    "Do you have a sunburn, or are you always this hot?",
    "You are so beautiful that I would marry your brother just to get into your family.",
    "You look like a cool glass of refreshing water, and I am the thirstiest man in the world.",
    "Are you a tamale? \'Cause you\'re hot.",
    "You are so beautiful that you give the sun a reason to shine.",
     "Do you bleach your teeth? \'Cause your smile lights up the entire room like a candle in the dark. Let\'s go prove it.",
    "Your ass is so nice that it is a shame that you have to sit on it.",
    "Someone should call the police, because you just stole my heart!",
    "Stop, drop, and roll, baby. You are on fire.",
    "Baby, you\'re so hot, you make the equator look like the north pole.",
    "Come live in my heart, and pay no rent.",
    "You\'re hotter than Papa Bear\'s porridge.",
    "I hope there\'s a fire truck nearby, cause you\'re smokin\'!",
    "If it weren\'t for that DAMNED sun, you\'d be the hottest thing ever created.",
    "I just got dumped, and I think that you could make me feel better.",
    "You are a 9 - you\'d be a perfect 10 if you were with me.",
    "Excuse me, I\'d like to have kids someday, and I wanted to know how your parents created such a beautiful creature.",
    "You\'re so hot, I bet you could light a candle at 10 paces.",
    "I can\'t believe I\'ve been hear the entire evening with all these beautiful people and the moment I find \'The One\', all I have time to say is \"good bye\".",
    "Hey baby, you\'ve got something on your butt - my eyes!",
    "This isn\'t a beer belly, It\'s a fuel tank for a love machine.",
    "I don\'t know you, but I think I love you already.",
    "Here\'s the key to my house, my car... and my heart.",
    "Is your name Summer? \'Cause you are as hot as hell.",
    "If I had to choose between one night with you or winning the lottery...I would chose winning the lottery...but it would be close...real close...",
    "Do you have any sunscreen? \'Cause you are burning me up!",
    "See these keys? I wish I had the one to your heart.",
    "You\'re hotter than donut grease.",
    "Your eyes are as blue as window cleaner.",
    "Was that an earthquake or did you just rock my world?",
    "If you were a burger at McDonalds, you\'d be McGorgeous.",
    "Are your parents retarded, \'cause you sure are special.",
    "If you could put a price tag on beauty you\'d be worth more than Fort Knox.",
    "I must be dancing with the devil, because you\'re hot as hell.",
    "Are you the moon? Because even when it\'s dark, you still seem to shine.",
    "I never need to see the sun again because your eyes light up my world.",
    "If you were a steak you would be well done.",
    "It\'s dark in here. Wait! It\'s because all of the light is shining on you.",
    "Your hand looks heavy. Let me hold it for you.",
    "Are you a kidnapper? Because you just abducted my heart.",
    "Can you pull this heart-shaped arrow out of my butt? A damn little kid with wings shot me.",
    "Is your body from McDonald\'s? Cause I\'m lovin\' it!",
    "Are you a microwave oven? Cause you melt my heart.",
    "Did you get your license suspended for driving so many guys crazy?",
    "Are you a girl scout, cause you tie my heart in knots.",
    "You\'re so hot, I could bake cookies on you.",
    "You look beautiful today, just like every other day.",
    "Let\'s play Winnie the Pooh and get my nose stuck in your honey jar.",
    "When I\'m older, I\'ll look back at all of my crowning memories, and I\'ll think of the day my children were born, the day I got married, and the day that I met you.",
    "If beauty were time, you\'d be eternity.",
    "Is your car battery dead? Because I\'d like to jump you.",
    "I\'m lost. Can you tell me which road leads to your heart?",
    "Even if there wasn\'t gravity on earth, I\'d still fall for you.",
    "It\'s a good thing I wore gloves today. Otherwise you\'d be too hot to handle.",
    "Hello. Cupid called. He says to tell you that he needs my heart back."
  ]

  robot.hear /pickmeup/i, (res) ->
      res.send res.random PICKUPLINES
